site_name: Laboratorio de inteligencia artificial aplicada
site_url: 
theme:
  name: material
  logo: logo.png
  favicon: favicon.png
  nav:

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 

plugins:
  - social
  - search
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/castudil
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/cesar-astudillo-93137143
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
<<<<<<< HEAD
=======

>>>>>>> 9649a872d00b5111bb80bc8cf1d32f0de91b69a2
