site_name: Smart Mesck
site_url: 
theme:
  name: material
  logo: smart-mesck-logo.png
  favicon: smart-mesck-logo.png
  nav:

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 

plugins:
  - social
  - search
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DarkNacho
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://cttn.cl"  target="_blank" rel="noopener">Smart-Mesck</a>
